Repository MicrosoftDocs/xamarin-docs.ja-jp, pull requests merged in 2019-03, with the labels that each got.

#123 Java Api → Java API
  docs/tools/dotnet-embedding/index.md
Labels: Accepted, Linguistic Suggestion

#122 c#、f# → C#、F#
  docs/tools/dotnet-embedding/index.md
Labels: Accepted, Linguistic Suggestion

#121 c:\ユーザー\\AppData\ローカル\Android\android sdk\プラットフォーム → C:\Users\<userna…
  docs/android/troubleshooting/questions/xa-lollipop.md
Labels: Accepted, Linguistic Suggestion

#125 Fix inappropriate translation.
  docs/ios/app-fundamentals/delegates-protocols-and-events.md
Labels: Linguistic Suggestion

#124 Fix inappropriate translation.
  docs/ios/app-fundamentals/ios-code-only.md
Labels: Linguistic Suggestion, Partially Accepted

#137 Visual c# → Visual C#
  docs/ios/app-fundamentals/ios-code-only.md
Labels: Accepted, Linguistic Suggestion

#136 ピカソ → Picasso
  docs/android/platform/binding-java-library/troubleshooting-bindings.md
Labels: Accepted, Linguistic Suggestion

#138 Visual c# → Visual C#
  docs/ios/app-fundamentals/images-icons/launch-screens.md
Labels: Accepted, Linguistic Suggestion

#129 Fix inappropriate translation.
  docs/ios/internals/api.md
Labels: Accepted, Linguistic Suggestion

#130 Fix inappropriate translation.
  docs/ios/get-started/objective-c-developers/primer.md
Labels: Accepted, Linguistic Suggestion

#131 Fix inappropriate translation.
  docs/cross-platform/macios/nativetypes.md
Labels: Linguistic Suggestion

#132 Fix inappropriate translation.
  docs/ios/deploy-test/debugging-in-xamarin-ios.md
Labels: Linguistic Suggestion

#133 Fix inappropriate translation.
  docs/cross-platform/internals/available-assemblies.md
Labels: Linguistic Suggestion, Partially Accepted

#134 Fix inappropriate translation.
  docs/ios/app-fundamentals/delegates-protocols-and-events.md
Labels: Linguistic Suggestion

#135 Fix inappropriate translation.
  docs/ios/deploy-test/performance.md
Labels: Linguistic Suggestion, Partially Accepted

#139 Fix inappropriate translation.
  docs/ios/internals/api-design/index.md
Labels: Accepted, Linguistic Suggestion

#140 Fix inappropriate translation.
  docs/ios/internals/architecture.md
Labels: Accepted, Linguistic Suggestion

#141 Translate Preface to Enterprise App Development manually
  docs/xamarin-forms/enterprise-application-patterns/preface.md
Labels: Linguistic Suggestion, Partially Accepted
