Repository MicrosoftDocs/xamarin-docs.ja-jp, pull requests merged in 2019-07, with the labels that each got.

#159 Fix inaccurate translation
  docs/essentials/accelerometer.md
Labels: Accepted

#160 Fix inaccurate translation
  docs/essentials/geocoding.md
Labels: Accepted, Linguistic Suggestion

#161 Update index.md
  docs/essentials/index.md
Labels: Accepted, Linguistic Suggestion

#164 Update index.md
  docs/essentials/index.md
Labels: Accepted

#162 Fix inaccurate translation
  docs/essentials/app-information.md
Labels: Accepted, Linguistic Suggestion

#165 Suggest to fix typo
  docs/xamarin-forms/data-cloud/index.yml
Labels: Accepted

#177 Fix inaccurate translation
  docs/essentials/flashlight.md
Labels: Accepted

#176 Fix inaccurate translation
  docs/essentials/file-system-helpers.md
Labels: Accepted

#175 Fix inaccurate translation
  docs/essentials/email.md
Labels: Accepted

#174 Fix inaccurate translation
  docs/essentials/device-information.md
Labels: Accepted

#173 Fix inaccurate translation
  docs/essentials/device-display.md
Labels: Accepted

#172 Fix inaccurate translation
  docs/essentials/detect-shake.md
Labels: Accepted

#171 Fix inaccurate translation
  docs/essentials/connectivity.md
Labels: Accepted

#170 Fix inaccurate translation
  docs/essentials/compass.md
Labels: Accepted

#169 Fix inaccurate translation
  docs/essentials/color-converters.md
Labels: Accepted

#168 Fix inaccurate translation
  docs/essentials/clipboard.md
Labels: Accepted

#167 Fix inaccurate translation
  docs/essentials/battery.md
Labels: Accepted

#166 Fix inaccurate translation
  docs/essentials/barometer.md
Labels: Accepted

#196 Fix inaccurate translation
  docs/essentials/vibrate.md
Labels: Accepted

#195 Fix inaccurate translation
  docs/essentials/version-tracking.md
Labels: Accepted

#194 Fix inaccurate translation
  docs/essentials/unit-converters.md
Labels: Accepted

#193 Fix inaccurate translation
  docs/essentials/text-to-speech.md
Labels: Accepted

#192 Fix inaccurate translation
  docs/essentials/sms.md
Labels: Accepted

#191 Fix inaccurate translation
  docs/essentials/share.md
Labels: Accepted

#190 Fix inaccurate translation
  docs/essentials/secure-storage.md
Labels: Accepted

#189 Fix inaccurate translation
  docs/essentials/preferences.md
Labels: Accepted

#188 Fix inaccurate translation
  docs/essentials/platform-extensions.md
Labels: Accepted

#187 Fix inaccurate translation
  docs/essentials/phone-dialer.md
Labels: Accepted

#186 Fix inaccurate translation
  docs/essentials/orientation-sensor.md
Labels: Accepted

#185 Fix inaccurate translation
  docs/essentials/open-browser.md
Labels: Accepted

#184 Fix inaccurate translation
  docs/essentials/maps.md
Labels: Accepted

#183 Fix inaccurate translation
  docs/essentials/main-thread.md
Labels: Accepted

#182 Fix inaccurate translation
  docs/essentials/magnetometer.md
Labels: Accepted

#181 Fix inaccurate translation
  docs/essentials/launcher.md
Labels: Accepted

#180 Fix inaccurate translation
  docs/essentials/gyroscope.md
Labels: Accepted

#179 Fix inaccurate translation
  docs/essentials/geolocation.md
Labels: Accepted

#178 Fix inaccurate translation
  docs/essentials/geocoding.md
Labels: Accepted

#197 fix "「こんにちは, world!」"→""Hello, world!""
  docs/graphics-games/urhosharp/index.md
Labels: Accepted

#163 Suggest to improve translations
  docs/whats-new/index.yml
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#198 fixed inappropriate japanese "による UrhoSharp のプログラミングF#"→"F＃ を使った Urho…
  docs/graphics-games/urhosharp/fsharp.md
Labels: Accepted, Linguistic Suggestion

#199 fix translation
  docs/cross-platform/macios/index.md
Labels: Accepted, Linguistic Suggestion

#200 fix translation
  docs/ios/internals/architecture.md
Labels: Accepted, Linguistic Suggestion
