Repository MicrosoftDocs/xamarin-docs.ja-jp, pull requests merged in 2019-05, with the labels that each got.

#147 fix Japanese sentences
  docs/xamarin-forms/user-interface/collectionview/layout.md
Labels: Linguistic Suggestion, Partially Accepted

#148 Back-Translation [値] → [value]
  docs/android/get-started/java-developers.md
Labels: In Progress

#149 Typo Java Api → Java API
  docs/android/internals/index.md
Labels: In Progress, Linguistic Suggestion

#150 Typo Api → API
  docs/android/internals/architecture.md
Labels: In Progress

#152 Typo Api → API
  docs/android/platform/renderscript.md
Labels: In Progress

#151 Typo Api → API
  docs/android/platform/binding-java-library/customizing-bindings/java-bindings-metadata.md
Labels: In Progress

#153 Typo .Apk → .apk
  docs/android/platform/native-libraries.md
Labels: Accepted, Linguistic Suggestion

#154 fixed inappropriate japanese "ユーザー補助の android Api" → "Androidのアクセシビリテ…
  docs/android/app-fundamentals/accessibility.md
Labels: Accepted, Linguistic Suggestion

#155 [LOC] Back-Translation "ノードの追加"→"add-node","ノードを削除"→"remove-node"
  docs/android/platform/binding-java-library/customizing-bindings/java-bindings-metadata.md
Labels: In Progress
