Repository MicrosoftDocs/xamarin-docs.ja-jp, pull requests merged in 2019-10, with the labels that each got.

#231 Fix image link
  docs/xamarin-forms/user-interface/menuitem.md
Labels: Accepted, Linguistic Suggestion

#232 Fix inaccurate translation
  docs/essentials/index.md
Labels: Accepted, Linguistic Suggestion

#235 Fix replacees
  docs/android/platform/files/external-storage.md
  docs/ios/app-fundamentals/images-icons/displaying-an-image.md
Labels: Accepted, Technical Issue

#233 Fix translation.
  docs/ios/internals/index.md
Labels: Accepted, Linguistic Suggestion

#234 Fix translation
  docs/ios/internals/api-design/index.md
Labels: Accepted, Linguistic Suggestion

#238 目標 C -> Objective-C
  docs/ios/internals/objective-c-selectors.md
Labels: Accepted, Linguistic Suggestion

#236 Fix translation
  docs/ios/internals/architecture.md
Labels: Accepted, Linguistic Suggestion

#239 Fix 'no__t'
  docs/android/platform/binding-java-library/binding-an-aar.md
  docs/xamarin-forms/platform/other/gtk.md
  docs/xamarin-forms/platform/other/tizen.md
  docs/xamarin-forms/platform/other/wpf.md
  docs/xamarin-forms/user-interface/controls/layouts.md
Labels: Accepted

#240 Fix 'no__t'
  docs/android/platform/android-10.md
Labels: Accepted

#241 Fix '@No__t_0'
  docs/xamarin-forms/platform/android/viewcell-context-actions.md
  docs/xamarin-forms/platform/windows/refreshview-pulldirection.md
  docs/xamarin-forms/user-interface/carouselview/emptyview.md
  docs/xamarin-forms/user-interface/carouselview/index.md
  docs/xamarin-forms/user-interface/carouselview/interaction.md
  docs/xamarin-forms/user-interface/carouselview/layout.md
  docs/xamarin-forms/user-interface/carouselview/populate-data.md
  docs/xamarin-forms/user-interface/carouselview/scrolling.md
  docs/xamarin-forms/user-interface/map/geocoder.md
  docs/xamarin-forms/user-interface/map/index.md
  docs/xamarin-forms/user-interface/map/pins.md
  docs/xamarin-forms/user-interface/map/polygons.md
  docs/xamarin-forms/user-interface/pop-ups.md
  docs/xamarin-forms/user-interface/refreshview.md
Labels: In Progress
