Repository MicrosoftDocs/xamarin-docs.ja-jp, pull requests merged in 2019-08, with the labels that each got.

#201 fix translation
  docs/ios/internals/objective-c-selectors.md
Labels: Accepted, Linguistic Suggestion

#204 [LOC] Back-Translation "ピカソ" → "Picasso"
  docs/android/platform/binding-java-library/binding-a-jar.md
Labels: Accepted

#203 fix trasnlation
  docs/ios/internals/index.md
Labels: Accepted, Linguistic Suggestion

#202 fix translation
  docs/cross-platform/macios/nativetypes.md
Labels: Accepted, Linguistic Suggestion

#206 fix translation
  docs/ios/platform/exception-marshaling.md
Labels: Accepted, Linguistic Suggestion

#207 fix translation
  docs/cross-platform/macios/optimizations.md
Labels: Accepted, Linguistic Suggestion

#205 fix translation
  docs/ios/app-fundamentals/ios-code-only.md
Labels: Accepted, Linguistic Suggestion

#210 fix translation
  docs/ios/internals/registrar.md
Labels: Accepted, Linguistic Suggestion

#209 fix translation
  docs/cross-platform/macios/optimizations.md
Labels: Accepted, Linguistic Suggestion

#208 fix translation
  docs/cross-platform/macios/optimizations.md
Labels: Accepted, Linguistic Suggestion

#212 fix translation
  docs/ios/internals/objective-c-selectors.md
Labels: Accepted, Linguistic Suggestion

#213 fix translation
  docs/ios/internals/architecture.md
Labels: Accepted, Linguistic Suggestion

#211 fix translation
  docs/ios/internals/architecture.md
Labels: Accepted, Linguistic Suggestion

#214 Suggest to fix 'Xamarin.Forms'
  docs/android/data-cloud/data-access/introduction.md
  docs/android/data-cloud/data-access/using-adonet.md
  docs/android/data-cloud/data-access/using-sqlite-orm.md
  docs/android/platform/speech.md
  docs/cross-platform/app-fundamentals/building-cross-platform-applications/architecture.md
  docs/cross-platform/app-fundamentals/building-cross-platform-applications/index.md
  docs/cross-platform/app-fundamentals/building-cross-platform-applications/overview.md
  docs/cross-platform/cpp/index.md
  docs/cross-platform/data-cloud/web-services/index.md
  docs/cross-platform/desktop/samples.md
  docs/cross-platform/macios/native-types-cross-platform.md
  docs/cross-platform/macios/unified/overview.md
  docs/cross-platform/macios/unified/updating-apps.md
  docs/cross-platform/macios/unified/updating-tips.md
  docs/cross-platform/macios/unified/updating-xamarin-forms-apps.md
  docs/cross-platform/platform/fsharp/samples.md
  docs/get-started/quickstarts/database.md
  docs/get-started/quickstarts/deepdive.md
  docs/get-started/quickstarts/multi-page.md
  docs/get-started/quickstarts/single-page.md
  docs/get-started/quickstarts/styling.md
  docs/ios/app-fundamentals/localization/index.md
  docs/ios/data-cloud/data/index.md
  docs/ios/data-cloud/data/introduction.md
  docs/ios/data-cloud/data/using-adonet.md
  docs/ios/data-cloud/data/using-data-in-an-app.md
  docs/ios/data-cloud/data/using-sqlite-orm.md
  docs/ios/user-interface/ios-ui/introduction-to-the-appearance-api.md
Labels: Accepted, Linguistic Suggestion

#217 Fix image link
  docs/get-started/quickstarts/database.md
Labels: Accepted, Source Issue

#215 Fix translation
  docs/ios/internals/registrar.md
Labels: Accepted, Linguistic Suggestion

#216 Fix translation
  docs/ios/internals/registrar.md
Labels: Accepted, Linguistic Suggestion

#219 Fix translation
  docs/ios/internals/registrar.md
Labels: Accepted, Linguistic Suggestion

#220 Suggest to fix a title
  docs/xamarin-forms/user-interface/layouts/index.yml
Labels: Accepted, Linguistic Suggestion

#221 Fix image link
  docs/xamarin-forms/user-interface/collectionview/introduction.md
Labels: Accepted

#218 Fix mistake of original text
  docs/ios/internals/api-design/index.md
Labels: Accepted, Source Issue
