Repository MicrosoftDocs/xamarin-docs.ja-jp, pull requests merged in 2020-01, with the labels that each got.

#266 Improve translations on "what's new"
  docs/whats-new/2019-03.md
  docs/whats-new/2019-08.md
  docs/whats-new/2019-10.md
  docs/whats-new/TOC.yml
Labels: Accepted, Linguistic Suggestion

#273 Fix translation
  docs/cross-platform/macios/binding/binding-types-reference.md
Labels: Accepted, Linguistic Suggestion

#268 Fix terminology mistakes.
  docs/cross-platform/macios/unified/updating-ios-apps.md
Labels: Accepted, Linguistic Suggestion

#267 Fix terminology mistakes
  docs/cross-platform/macios/index.md
Labels: Accepted, Linguistic Suggestion

#270 Fix inappropriate translations.
  docs/ios/internals/api.md
Labels: Accepted, Linguistic Suggestion

#269 Fix terminology mistakes.
  docs/cross-platform/macios/unified/updating-apps.md
Labels: Accepted, Linguistic Suggestion

#272 [LOC]Back-Translation "[共有ユーザー設定]"→"[Shared Preferences]"
  docs/essentials/preferences.md
Labels: Accepted, Linguistic Suggestion

#275 Fix translation
  docs/ios/internals/api-design/nsstring.md
Labels: Accepted, Linguistic Suggestion

#274 Fix translation
  docs/ios/internals/api-design/index.md
Labels: Accepted, Linguistic Suggestion

#271 [LOC]Back-Translation "[共有ユーザー設定]"→"[Shared Preferences]"
  docs/essentials/preferences.md
Labels: Accepted, Linguistic Suggestion

#277 Fix translation
  docs/ios/internals/limitations.md
Labels: Accepted

#278 Fix translation
  docs/ios/internals/objective-c-selectors.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue

#280 Improve translations
  docs/ios/platform/touch-id-face-id.md
Labels: Accepted, Linguistic Suggestion

#283 Fix translation
  docs/ios/troubleshooting/index.md
Labels: Accepted

#281 Fix translation
  docs/cross-platform/internals/available-assemblies.md
Labels: Accepted

#276 Fix translation
  docs/ios/internals/architecture.md
Labels: Accepted, Linguistic Suggestion

#284 Fix translation
  docs/ios/internals/api-design/index.md
Labels: Accepted

#286 Fix translation
  docs/ios/app-fundamentals/delegates-protocols-and-events.md
Labels: Accepted, Linguistic Suggestion

#288 Fix tanslation
  docs/cross-platform/macios/native-types-cross-platform.md
Labels: Accepted

#287 Fix translation
  docs/ios/internals/architecture.md
Labels: Accepted, Linguistic Suggestion

#291 Fix translation
  docs/ios/internals/registrar.md
Labels: Accepted, Linguistic Suggestion

#292 Fix translation
  docs/ios/app-fundamentals/index.md
Labels: Accepted, Linguistic Suggestion

#295 Fix translation
  docs/ios/internals/api-design/index.md
Labels: Accepted, Linguistic Suggestion

#297 Fix translations
  docs/ios/platform/extensions.md
Labels: Accepted, Linguistic Suggestion

#293 Unify the term "Xamarin.Forms"
  docs/get-started/quickstarts/index.md
Labels: Accepted, Linguistic Suggestion

#282 Fix translation
  docs/ios/internals/floating-point.md
Labels: Accepted, Linguistic Suggestion

#289 Fix translation
  docs/cross-platform/macios/http-stack.md
Labels: Accepted, Linguistic Suggestion

#290 Fix translation
  docs/cross-platform/macios/32-and-64/index.md
Labels: Accepted, Linguistic Suggestion

#294 Fix image alt text, improve translations
  docs/ios/user-interface/controls/webview.md
Labels: Accepted, Linguistic Suggestion

#296 Fix translation
  docs/ios/internals/api.md
Labels: Accepted, Linguistic Suggestion

#305 Improve translation
  docs/ios/get-started/installation/windows/index.md
Labels: Accepted, Linguistic Suggestion

#306 Improve translation
  docs/ios/get-started/hello-ios/hello-ios-quickstart.md
Labels: Accepted, Linguistic Suggestion

#307 Improve translation
  docs/ios/get-started/hello-ios/hello-ios-deepdive.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#308 Improve translations
  docs/ios/get-started/hello-ios/hello-ios-deepdive.md
Labels: Accepted, Technical Issue

#309 Improve translation
  docs/ios/deploy-test/ios-build-mechanics.md
Labels: Accepted, Linguistic Suggestion
