Repository MicrosoftDocs/xamarin-docs.ja-jp, pull requests merged in 2020-04, with the labels that each got.

#382 Fix translations for 'label'
  docs/get-started/TOC.yml
  docs/get-started/index.yml
  docs/get-started/tutorials/index.yml
  docs/xamarin-forms/TOC.yml
  docs/xamarin-forms/user-interface/index.yml
Labels: Accepted, Linguistic Suggestion

#383 improve translations
  docs/xamarin-forms/app-fundamentals/shell/index.md
Labels: Accepted, Linguistic Suggestion

#384 Improve translations
  docs/android/get-started/installation/android-emulator/index.md
Labels: Accepted, Technical Issue

#403 Fix translations
  docs/android/troubleshooting/questions/index.md
Labels: Accepted

#402 Fix translations
  docs/android/get-started/installation/windows.md
Labels: Accepted

#399 Fix translations
  docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive.md
Labels: Accepted

#398 Fix translations
  docs/android/deploy-test/release-prep/index.md
Labels: Accepted, Technical Issue

#396 Fix translations
  docs/android/deploy-test/install-system-app.md
Labels: Accepted, Technical Issue

#408 Fix translations
  docs/essentials/open-browser.md
Labels: Accepted

#406 Fix translations
  docs/cross-platform/includes/install-xamarin-windows.md
Labels: Accepted

#395 Fix translations
  docs/android/deploy-test/debugging/debug-on-emulator.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#397 Fix translations
  docs/android/deploy-test/publishing/publishing-to-google-play/index.md
Labels: Accepted, Linguistic Suggestion

#400 Fix translations
  docs/android/get-started/hello-android/hello-android-deepdive.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#401 Fix translations
  docs/android/get-started/installation/android-sdk.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#404 Fix translations
  docs/cross-platform/deploy-test/multi-process-debugging.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#405 Fix translations
  docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive.md
Labels: Accepted, Linguistic Suggestion

#407 Fix translations
  docs/essentials/main-thread.md
Labels: Accepted, Linguistic Suggestion

#409 Fix translations
  docs/essentials/preferences.md
Labels: Accepted, Linguistic Suggestion

#418 Fix translations
  docs/android/get-started/installation/windows.md
Labels: Accepted

#414 Fix translations
  docs/android/deploy-test/release-prep/index.md
Labels: Accepted

#412 Fix translations
  docs/android/deploy-test/install-system-app.md
Labels: Accepted

#421 Fix translations
  docs/cross-platform/includes/install-xamarin-windows.md
Labels: Accepted

#417 Fix translations
  docs/android/get-started/installation/android-sdk.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#416 Fix translations
  docs/android/get-started/installation/android-emulator/index.md
Labels: Accepted, Linguistic Suggestion

#415 Fix translations
  docs/android/get-started/hello-android/hello-android-deepdive.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#413 Fix translations
  docs/android/deploy-test/publishing/publishing-to-google-play/index.md
Labels: Accepted, Linguistic Suggestion

#411 Fix translations
  docs/android/deploy-test/debugging/debug-on-emulator.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#422 Fix translations
  docs/essentials/main-thread.md
Labels: Accepted, Linguistic Suggestion

#420 Fix translations
  docs/cross-platform/deploy-test/multi-process-debugging.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#419 Fix translations
  docs/android/troubleshooting/questions/index.md
Labels: Accepted, Linguistic Suggestion

#423 Suggestion: "ビルドするための" -> "開発するための"
  docs/get-started/what-is-xamarin.md
Labels: Accepted, Linguistic Suggestion
